# Generated by Django 4.2.14 on 2024-08-07 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_roll_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 5, 4, 52, 249261, tzinfo=datetime.timezone.utc)),
        ),
    ]
