# Generated by Django 4.2.14 on 2024-08-07 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notifications_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 5, 48, 32, 152382, tzinfo=datetime.timezone.utc)),
        ),
    ]
