# Generated by Django 4.2.14 on 2024-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_stocklevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookspecifications',
            name='book_publishing_date',
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_ISBN_13',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_binding',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookspecifications',
            name='book_total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
