# Generated by Django 4.2.14 on 2024-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_stocklevel_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.5, max_digits=2, null=True),
        ),
    ]
