# Generated by Django 4.2.14 on 2024-09-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0008_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookspecifications",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_specifications",
                to="bookstore.book",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="bookstore.book",
            ),
        ),
        migrations.AlterField(
            model_name="stocklevel",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_level",
                to="bookstore.book",
            ),
        ),
    ]
