# Generated by Django 4.2.14 on 2024-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numbers_of_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
