# Generated by Django 4.2.14 on 2024-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order_numbers_of_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price_original",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
