# Generated by Django 4.2.14 on 2024-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_discounted_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
